default_platform(:ios)

platform :ios do
  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_content: ENV["ASC_PRIVATE_KEY"],
      is_key_content_base64: true,
      in_house: false # detecting this via ASC private key not currently supported
    )
  end
 end

 desc "Bump build number based on most recent TestFlight build number"
 lane :fetch_and_increment_build_number do
  #fetch read your app identifier defined in your Appfile
  app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]
 
  current_version = get_version_number(
    target: "DagestanTrails" # replace with your main target, required if you have more than one non-test target
  )
  latest_build_number = latest_testflight_build_number(
    api_key: api_key,
    version: current_version,
    app_identifier: app_identifier
  )
  increment_build_number(
    build_number: (latest_build_number + 1),
  )
 end
 
 
 desc "Installs signing certificate in the keychain and downloads provisioning profiles from App Store Connect"
 lane :prepare_signing do |options|
   team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
   api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

   keychain_name = "signing"
   keychain_password = "temp"

   delete_keychain(
     name: keychain_name
   ) if File.exist? File.expand_path("~/Library/Keychains/#{keychain_name}-db")

   create_keychain(
     name: keychain_name,
     password: keychain_password,
     default_keychain: true,
     unlock: true,
     timeout: 3600
   )

   import_certificate(
     certificate_path: ENV["SIGNING_KEY_FILE_PATH"],
     certificate_password: ENV["SIGNING_KEY_PASSWORD"],
     keychain_name: keychain_name,
     keychain_password: keychain_password
   )

   # fetches and installs provisioning profiles from ASC
   sigh(
     adhoc: options[:adhoc],
     api_key: api_key,
     readonly: true
   )
 end
 
desc "Generate xcode project with tuist"
lane :generate_project do
    sh "mise x -- tuist clean --path ../"
    sh "mise x -- tuist install --path ../"
    sh "mise x -- tuist generate --path ../"
  end
end

 desc "Build the iOS app for release"
 lane :build_release do |options|
  app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
 
  profile_name = "Ramazan Abdulaev" # replace with the name of the profile to use for the build
  output_name = "DagestanTrails-iOS" # specify the name of the .ipa file to generate
  export_method = "app-store" # specify the export method
 
  # turn off automatic signing during build so correct code signing identity is guaranteed to be used
  update_code_signing_settings(
    use_automatic_signing: false,
    targets: ["DagestanTrails"], # specify which targets to update code signing settings for
    code_sign_identity: "Apple Distribution", # replace with name of code signing identity if different
    bundle_identifier: app_identifier,
    profile_name: profile_name,
    build_configurations: ["Release"] # only toggle code signing settings for Release configurations
  )
 # build the app
 gym(
   scheme: "DagestanTrails", # replace with name of your project’s scheme
   output_name: output_name,
   configuration: "Release",
   export_options: {
     method: export_method,
     provisioningProfiles: {
       app_identifier => profile_name # here you can add any additional bundle identifiers and their associated provisioning profiles if you’re also building an app extension or other bundle identifier
     }
   }
 )
end

desc "Upload to TestFlight / ASC"
lane :upload_release do
 api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

 deliver(
     api_key: api_key,
     skip_screenshots: true,
     skip_metadata: true,
     skip_app_version_update: true,
     force: true, # skips verification of HTML preview file (since this will be run from a CI machine)
     run_precheck_before_submit: false # not supported through ASC API yet
 )
end




# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
#     sh "mise x -- tuist clean --path ../"
#     sh "mise x -- tuist install --path ../"
#     sh "mise x -- tuist generate --path ../"
#     update_project_team(
#       path: "DagestanTrails.xcodeproj",
#       teamid: "CW9ZZNL977"
#     )
#     api_key = app_store_connect_api_key(
#       key_id: "5XBBKZTV6V",
#       issuer_id: "e970bf8c-3de3-4898-8797-a0a317a62512",
#       key_filepath: "/Users/txmi/dagestan-ios/Dagestan/fastlane/AuthKey_5XBBKZTV6V.p8",
#       duration: 1200,
#       in_house: false
#     )
    
#     build_app(
# 	scheme: "DagestanTrails", 
#     	buildlog_path: "./fastlane/build_output"
#     )
#     upload_to_testflight(api_key: api_key, app_identifier: "com.WayFlare.DagestanTrails")
#   end
# end
